// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

namespace WebApp.Migrations.Subtheme
{
    [DbContext(typeof(SubthemeContext))]
    [Migration("20220913150139_4eme")]
    partial class _4eme
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Models.subtheme", b =>
                {
                    b.Property<int>("subthemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ThemeID")
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("subthemeId");

                    b.HasIndex("ThemeID");

                    b.ToTable("subtheme");

                    b.HasData(
                        new
                        {
                            subthemeId = 1,
                            nom = "Camping"
                        },
                        new
                        {
                            subthemeId = 2,
                            nom = "Hicking"
                        },
                        new
                        {
                            subthemeId = 3,
                            nom = "Prepare meals in nature"
                        },
                        new
                        {
                            subthemeId = 4,
                            nom = "walking"
                        },
                        new
                        {
                            subthemeId = 5,
                            nom = "hunt"
                        },
                        new
                        {
                            subthemeId = 6,
                            nom = "fishing"
                        },
                        new
                        {
                            subthemeId = 7,
                            nom = "sand diving"
                        },
                        new
                        {
                            subthemeId = 8,
                            nom = "Ski Palmier"
                        },
                        new
                        {
                            subthemeId = 9,
                            nom = "Back packing"
                        },
                        new
                        {
                            subthemeId = 10,
                            nom = "Night sky"
                        },
                        new
                        {
                            subthemeId = 11,
                            nom = "Back packing"
                        },
                        new
                        {
                            subthemeId = 12,
                            nom = "Nature and ecology tour"
                        },
                        new
                        {
                            subthemeId = 13,
                            nom = "plante et agriculture"
                        },
                        new
                        {
                            subthemeId = 14,
                            nom = "Activité plein air"
                        },
                        new
                        {
                            subthemeId = 15,
                            nom = "Beauté"
                        },
                        new
                        {
                            subthemeId = 16,
                            nom = "spa"
                        },
                        new
                        {
                            subthemeId = 17,
                            nom = "pleine conscience"
                        },
                        new
                        {
                            subthemeId = 18,
                            nom = "thérapie de corps"
                        },
                        new
                        {
                            subthemeId = 19,
                            nom = "Etat d’esprit"
                        },
                        new
                        {
                            subthemeId = 20,
                            nom = "Yoga"
                        },
                        new
                        {
                            subthemeId = 21,
                            nom = "santé holistique"
                        },
                        new
                        {
                            subthemeId = 22,
                            nom = "Divination"
                        },
                        new
                        {
                            subthemeId = 23,
                            nom = "Autre Expérience Bien-être"
                        },
                        new
                        {
                            subthemeId = 24,
                            nom = "cuisineet alimentation"
                        },
                        new
                        {
                            subthemeId = 25,
                            nom = "degustation gastronomique"
                        },
                        new
                        {
                            subthemeId = 26,
                            nom = "diner en groupe"
                        },
                        new
                        {
                            subthemeId = 27,
                            nom = "Visite de marché et gastronomie"
                        },
                        new
                        {
                            subthemeId = 28,
                            nom = "sport"
                        },
                        new
                        {
                            subthemeId = 29,
                            nom = "sycling"
                        },
                        new
                        {
                            subthemeId = 30,
                            nom = "Divertissement"
                        },
                        new
                        {
                            subthemeId = 31,
                            nom = "Cours sur l’entrepreneuriat"
                        },
                        new
                        {
                            subthemeId = 32,
                            nom = "Conférence culturelle"
                        },
                        new
                        {
                            subthemeId = 33,
                            nom = "Cours de langue "
                        },
                        new
                        {
                            subthemeId = 34,
                            nom = " Visite d’usine"
                        },
                        new
                        {
                            subthemeId = 35,
                            nom = "Visite de campagne "
                        },
                        new
                        {
                            subthemeId = 36,
                            nom = " Autre activité culturelle"
                        },
                        new
                        {
                            subthemeId = 37,
                            nom = " Cours de sciences "
                        },
                        new
                        {
                            subthemeId = 38,
                            nom = "conférence sur des enjeux sociaux"
                        },
                        new
                        {
                            subthemeId = 39,
                            nom = "Danse culturelle"
                        },
                        new
                        {
                            subthemeId = 40,
                            nom = "Visite culturelle "
                        },
                        new
                        {
                            subthemeId = 41,
                            nom = "visite de bureau"
                        },
                        new
                        {
                            subthemeId = 42,
                            nom = " Festival Culturelle"
                        },
                        new
                        {
                            subthemeId = 43,
                            nom = " Mariage traditionnelle"
                        },
                        new
                        {
                            subthemeId = 44,
                            nom = "tatouage traditionnelle "
                        },
                        new
                        {
                            subthemeId = 45,
                            nom = " Vivre une experience avec une famille"
                        },
                        new
                        {
                            subthemeId = 46,
                            nom = "SeaDiving"
                        },
                        new
                        {
                            subthemeId = 47,
                            nom = "Parachute"
                        },
                        new
                        {
                            subthemeId = 48,
                            nom = " Location pédale a eau/bateau"
                        },
                        new
                        {
                            subthemeId = 49,
                            nom = "Snorking"
                        },
                        new
                        {
                            subthemeId = 50,
                            nom = " Bataille d’eau "
                        },
                        new
                        {
                            subthemeId = 51,
                            nom = "Apprendre à nager"
                        },
                        new
                        {
                            subthemeId = 52,
                            nom = "sport nautrique"
                        },
                        new
                        {
                            subthemeId = 53,
                            nom = "chercher des coquillages "
                        },
                        new
                        {
                            subthemeId = 54,
                            nom = "Bâtir des châteaux de sable"
                        },
                        new
                        {
                            subthemeId = 55,
                            nom = "S’enterrer dans les sables"
                        },
                        new
                        {
                            subthemeId = 56,
                            nom = "Morpion dans le sable"
                        },
                        new
                        {
                            subthemeId = 57,
                            nom = "découvrir le chair à voile "
                        },
                        new
                        {
                            subthemeId = 58,
                            nom = "Jeux de ballon"
                        },
                        new
                        {
                            subthemeId = 59,
                            nom = "Jetski"
                        },
                        new
                        {
                            subthemeId = 60,
                            nom = "shooping"
                        },
                        new
                        {
                            subthemeId = 61,
                            nom = "boisson"
                        },
                        new
                        {
                            subthemeId = 62,
                            nom = "animaux"
                        },
                        new
                        {
                            subthemeId = 63,
                            nom = "gambling"
                        },
                        new
                        {
                            subthemeId = 64,
                            nom = "tour de bar"
                        });
                });

            modelBuilder.Entity("WebApp.Models.theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThemeID");

                    b.ToTable("theme");

                    b.HasData(
                        new
                        {
                            ThemeID = 1,
                            name = "nature"
                        },
                        new
                        {
                            ThemeID = 2,
                            name = "health"
                        },
                        new
                        {
                            ThemeID = 3,
                            name = "food"
                        },
                        new
                        {
                            ThemeID = 4,
                            name = "event"
                        },
                        new
                        {
                            ThemeID = 5,
                            name = "culture"
                        },
                        new
                        {
                            ThemeID = 6,
                            name = "seaside"
                        },
                        new
                        {
                            ThemeID = 7,
                            name = "autres"
                        });
                });

            modelBuilder.Entity("WebApp.Models.subtheme", b =>
                {
                    b.HasOne("WebApp.Models.theme", "theme")
                        .WithMany()
                        .HasForeignKey("ThemeID");

                    b.Navigation("theme");
                });
#pragma warning restore 612, 618
        }
    }
}
